language: python

python: 3.6
sudo: required

dist: xenial

stages:
  - name: style guide
    if: type IN (push, pull_request)

jobs:
  include:
    - stage: style guide
      python: 3.6
      before_script:
        - pip install tox-travis
      script: tox

notifications:
  email: false
