apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inbox-storage
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi #Make this bigger in production.
